# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - celonis-sentiment-analysis

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_12a4fa2973c54479a950ee20d048bb6a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0821d3ecb9844417b98c6d23ca932f80 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_12a4fa2973c54479a950ee20d048bb6a }}/deidatalab/sentiment-analysis:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'celonis-sentiment-analysis'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c62f0342b2ad459197d2786a00682aaf }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_12a4fa2973c54479a950ee20d048bb6a }}/deidatalab/sentiment-analysis:${{ github.sha }}'